version: 0.2

env:
  variables:
    foo: "bar"
    RAILS_ENV: "test"

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Ruby code...
      - rspec 
    finally:
      - echo "Finally block of build phase reached.  this executes even if the commands in this phase error out."
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - config.ru 
